server:
  port: 40001

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/h2db;MODE=MySQL;
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 20

logging:
  level:
    kr.ac.knu.cse: DEBUG
    org:
      springframework:
        security: DEBUG
        security.oauth2: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

app:
  frontend: # Frontend URL Configuration
    base-url: http://localhost:3000

keycloak:
  base-url: http://localhost:8080
  realm: your-realm
  admin:
    client-id: admin-cli-client
    client-secret: admin-cli-secret

sso:
  redirect-allowlist:
    - https://service-a.example.com/auth/callback
    - https://service-b.example.com/auth/callback


